(()=>{'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
function ready(fn){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn()}
ready(()=>{initLoader();initTheme();initNav();initHeader();initProgress();initActiveNav();initCounters();initReveal();initTyping();initCursor();initCardGlow();initParticles();initProfileImage();initYear()});
function initLoader(){const l=$('#loading-screen');if(!l)return;setTimeout(()=>l.classList.add('hidden'),reduce?100:1200)}
function initTheme(){const t=$('#theme-toggle');if(!t)return;const apply=x=>{document.documentElement.dataset.theme=x;localStorage.setItem('portfolio-theme',x)};apply(localStorage.getItem('portfolio-theme')||'dark');t.onclick=()=>apply(document.documentElement.dataset.theme==='light'?'dark':'light')}
function initNav(){const b=$('#mobile-menu-toggle'),n=$('#primary-navigation');if(!b||!n)return;const close=()=>{b.setAttribute('aria-expanded','false');n.classList.remove('is-open');document.body.classList.remove('nav-open')};b.onclick=()=>{const open=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(open));n.classList.toggle('is-open',open);document.body.classList.toggle('nav-open',open)};$$('#primary-navigation a').forEach(a=>a.addEventListener('click',close));addEventListener('keydown',e=>e.key==='Escape'&&close());addEventListener('resize',()=>innerWidth>800&&close())}
function initHeader(){const h=$('#site-header');if(!h)return;const u=()=>h.classList.toggle('scrolled',scrollY>20);u();addEventListener('scroll',u,{passive:true})}
function initProgress(){const p=$('#scroll-progress');if(!p)return;const u=()=>{const max=document.documentElement.scrollHeight-innerHeight;p.style.width=(max?scrollY/max*100:0)+'%'};u();addEventListener('scroll',u,{passive:true});addEventListener('resize',u,{passive:true})}
function initActiveNav(){const links=$$('.nav-link'),sections=links.map(a=>$(a.getAttribute('href'))).filter(Boolean);if(!sections.length||!('IntersectionObserver'in window))return;const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-35% 0px -55% 0px'});sections.forEach(s=>io.observe(s))}
function initCounters(){const els=$$('.stat-number');if(reduce){els.forEach(e=>e.textContent=e.dataset.target+e.dataset.suffix);return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){animate(e.target);io.unobserve(e.target)}}),{threshold:.5});els.forEach(e=>io.observe(e));function animate(el){const target=+el.dataset.target,s=el.dataset.suffix||'',dec=target%1?1:0,start=performance.now(),dur=1200;function f(now){const p=Math.min(1,(now-start)/dur),v=target*(1-Math.pow(1-p,3));el.textContent=v.toFixed(dec)+s;if(p<1)requestAnimationFrame(f)}requestAnimationFrame(f)}}
function initReveal(){const els=$$('.reveal,.skill-category,.cert-card,.value-props article,.glass-card,.timeline-item');if(reduce){els.forEach(e=>e.classList.add('visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -40px'});els.forEach(e=>{if(!e.classList.contains('reveal'))e.classList.add('reveal');io.observe(e)})}
function initTyping(){const el=$('#typing-text');if(!el||reduce)return;const words=['Enterprise IT Support & Infrastructure','Microsoft 365 • Azure • Entra ID','Windows Server • Networking • NOC','Service Desk L3 • Incident Management'];let i=0,j=0,del=false;function tick(){const w=words[i];el.textContent=w.slice(0,j);if(!del&&j<w.length){j++;setTimeout(tick,55)}else if(!del){del=true;setTimeout(tick,1600)}else if(j>0){j--;setTimeout(tick,28)}else{del=false;i=(i+1)%words.length;setTimeout(tick,250)}}tick()}
function initCursor(){if(reduce||innerWidth<801)return;const c=$('#cursor'),d=$('#cursor-dot');if(!c||!d)return;document.body.style.cursor='none';let x=-100,y=-100,tx=-100,ty=-100;addEventListener('mousemove',e=>{tx=e.clientX;ty=e.clientY;d.style.left=tx+'px';d.style.top=ty+'px'});function f(){x+=(tx-x)*.18;y+=(ty-y)*.18;c.style.left=x+'px';c.style.top=y+'px';requestAnimationFrame(f)}f();$$('a,button,.glass-card,.skill-category,.cert-card,.value-props article').forEach(e=>{e.addEventListener('mouseenter',()=>c.classList.add('hover'));e.addEventListener('mouseleave',()=>c.classList.remove('hover'))})}
function initCardGlow(){if(reduce)return;const cards=$$('.glass-card,.skill-category,.cert-card,.timeline-card,.lab-grid>div,.value-props article,.recommendation blockquote');cards.forEach(card=>card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.setProperty('--mx',`${e.clientX-r.left}px`);card.style.setProperty('--my',`${e.clientY-r.top}px`)}));}
function initParticles(){if(reduce)return;const cv=$('#particles-canvas');if(!cv)return;cv.style.position='fixed';cv.style.inset='0';cv.style.width='100%';cv.style.height='100%';cv.style.pointerEvents='none';cv.style.zIndex='0';const ctx=cv.getContext('2d');let w,h,pts=[];const resize=()=>{w=cv.width=innerWidth*devicePixelRatio;h=cv.height=innerHeight*devicePixelRatio;cv.style.width=innerWidth+'px';cv.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);pts=Array.from({length:Math.min(80,Math.floor(innerWidth/16))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.35,vy:(Math.random()-.5)*.35,r:Math.random()*1.6+.5}))};resize();addEventListener('resize',resize,{passive:true});function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);for(const p of pts){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>innerWidth)p.vx*=-1;if(p.y<0||p.y>innerHeight)p.vy*=-1;ctx.fillStyle='rgba(56,189,248,.55)';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){const a=pts[i],b=pts[j],dx=a.x-b.x,dy=a.y-b.y,dist=Math.hypot(dx,dy);if(dist<125){ctx.strokeStyle=`rgba(56,189,248,${.12*(1-dist/125)})`;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}requestAnimationFrame(draw)}draw()}
function initProfileImage(){const avatar=$('.hero-avatar');if(!avatar)return;if(avatar.querySelector('img'))return;const img=document.createElement('img');img.src='https://raw.githubusercontent.com/rictuazon17/ric-portfolio-site/main/123.jpg';img.alt='Ricardo Tuazon Jr. - Senior IT Support Engineer';img.loading='eager';img.decoding='async';img.referrerPolicy='no-referrer';Object.assign(img.style,{position:'absolute',inset:'8px',width:'calc(100% - 16px)',height:'calc(100% - 16px)',objectFit:'cover',borderRadius:'50%',zIndex:'2'});avatar.style.position='relative';avatar.style.overflow='hidden';const text=[...avatar.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE||n.nodeType===Node.ELEMENT_NODE);text.forEach(n=>{if(n!==img)n.style&&(n.style.opacity='0')});avatar.appendChild(img);img.onerror=()=>{img.remove();avatar.style.overflow='visible';text.forEach(n=>n.style&&(n.style.opacity='1'))}}
function initYear(){const y=$('#year');if(y)y.textContent=new Date().getFullYear()}
})();
